branches:
  only:
    - master

language:
  - c

before_install:
  - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
  - sudo apt-get update
  - sudo apt-get install -y gcc-arm-none-eabi symlinks build-essential

before_script:
  - arm-none-eabi-gcc --version

compiler:
  - gcc

script:
  - make clean
  - make

notifications:
  email:
    recipients:
      - chiacheng.tsao@gmail.com
    on_success:
      - always
    on_failure:
      - always
