language: c
before_install:
 - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
 - sudo apt-get update
 - sudo apt-get install gperf
 - sudo apt-get install valgrind
 - sudo apt-get install gcc-arm-none-eabi
before_script:
 - arm-none-eabi-gcc --version
compiler:
  - gcc
script: make
notifications:
  email:
    recipients:
      - chiacheng.tsao@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: releases
  api-key: $TOKEN
  file: "bin/ESC32.hex"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
